use_frameworks!
platform :ios, '9.0'

def google_utilites
  pod 'GoogleUtilities/AppDelegateSwizzler'
  pod 'GoogleUtilities/Environment'
  pod 'GoogleUtilities/ISASwizzler'
  pod 'GoogleUtilities/Logger'
  pod 'GoogleUtilities/MethodSwizzler'
  pod 'GoogleUtilities/NSData+zlib'
  pod 'GoogleUtilities/Network'
  pod 'GoogleUtilities/Reachability'
  pod 'GoogleUtilities/UserDefaults'
end

source 'https://github.com/CocoaPods/Specs.git'
target 'Travel Companion' do
    
    pod 'RxSwift'
    pod 'RxCocoa'
    
    google_utilites
    
    pod 'Firebase/Auth'
    pod 'Firebase/Core'
    pod 'Firebase/Firestore'
    pod 'Firebase/Performance'
    pod 'Firebase/RemoteConfig'
    pod 'Firebase/Storage'
    
    pod 'FirebaseUI'
    pod 'FirebaseUI/Auth'
    pod 'FirebaseUI/OAuth'
    pod 'FirebaseUI/Email'
    pod 'FirebaseUI/Google'
    pod 'FirebaseUI/Facebook'
    pod 'FirebaseUI/Email'
    
    pod 'CodableFirebase'
    pod 'Fabric', '~> 1.7.11'
    pod 'Crashlytics', '~> 3.10.7'
    
    pod 'GoogleMaps'
    pod 'GooglePlaces'
    
    pod 'HTMLEntities', :git => 'https://github.com/IBM-Swift/swift-html-entities.git'

    target 'Travel CompanionTests' do
        inherit! :search_paths
        
        google_utilites
        
        pod 'RxSwift'
        pod 'Firebase'
    end
end
